default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_41672_development


test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_41672_test

production:
  <<: *default
  adapter: mysql2
  database: furima_41672_production
  username: root
  url: <%= ENV['DATABASE_URL'] %>
  socket: /var/lib/mysql/mysql.sock